## 01. Numpy

- 다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리에 많이 사용됨

### 1-1. ndarray
- numpy의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [11]:
import numpy as np

In [13]:
# ndarray의 생성
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1.0, 3.14, 1.24])

# 배열의 구조
print(f"배열의 구조: {a.shape}")
print(f"배열의 구조: {b.shape}")

# 배열의 차원 수
print(f"배열의 차원 수: {a.ndim}")
print(f"배열의 차원 수: {b.ndim}")

# 데이터 타입
print(f"배열의 데이터 타입: {a.dtype}")
print(f"배열의 데이터 타입: {b.dtype}")

# 형변환
new_a = a.astype(np.float64)
print(f"수정한 배열의 데이터 타입: {new_a.dtype}")

배열의 구조: (2, 3)
배열의 구조: (3,)
배열의 차원 수: 2
배열의 차원 수: 1
배열의 데이터 타입: int64
배열의 데이터 타입: float64
수정한 배열의 데이터 타입: float64


In [15]:
# 3차원 행렬
a = np.array([[[1, 2, 3], [4, 5, 6]], 
              [[1, 2, 3], [4, 5, 6]], 
              [[1, 2, 3], [4, 5, 6]]])

# 배열의 구조
print(f"배열의 구조: {a.shape}")

# 배열의 차원 수
print(f"배열의 차원 수: {a.ndim}")

배열의 구조: (3, 2, 3)
배열의 차원 수: 3


In [17]:
# 4차원 행렬
a = np.array([[[[1, 2, 3], [4, 5, 6]]], 
              [[[1, 2, 3], [4, 5, 6]]], 
              [[[1, 2, 3], [4, 5, 6]]],
              [[[1, 2, 3], [4, 5, 6]]]])

# 배열의 구조
print(f"배열의 구조: {a.shape}")

# 배열의 차원 수
print(f"배열의 차원 수: {a.ndim}")

배열의 구조: (4, 1, 2, 3)
배열의 차원 수: 4


### 1-2. 배열 초기화

In [ ]:
# 모든 요소가 0인 배열 생성
# np.zeros()에 넣는건 행렬의 구조를 넣는 것이다.
np.zeros((3, 4)) # 2차원 행렬

np.zeros((2, 3, 4), dtype = np.int64) # 3차원 행렬

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
# 모든 요소가 1인 배열 생성
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
# (원소의 값이) 초기화 되지 않는 배열 생성
np.empty((2, 3))

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [22]:
# 주어진 값으로 채운 배열
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [23]:
# 단위 행렬
np.eye(3, 3)
np.eye(3, 5, 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### 1-3. 범위 기반 배열 생성

In [26]:
# arrange: range()와 유사한 기능 제공
# 시작 이상 끝 미만의 정수 배열을 지정한 간격으로 생성
np.arange(0, 10)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [32]:
# linspace: 시작부터 끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
# 끝을 포함함

np.linspace(0.1, 1, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### 1-4. 랜덤 배열 생성

In [33]:
# random.rand(m, n): 0 ~ 1 사이의 난수로 초기화
np.random.rand(4, 5)

array([[0.86944688, 0.60548506, 0.86227618, 0.06118272, 0.60406916],
       [0.67911731, 0.15542913, 0.38719546, 0.82591535, 0.74841097],
       [0.0352395 , 0.9940761 , 0.83209666, 0.95752397, 0.60638962],
       [0.91956265, 0.65447285, 0.19668425, 0.67100713, 0.96866279]])

In [ ]:
# random.randn(m, n): 표준정규분포를 따를 난수로 초기화
#  표준정규분포: 평균 0, 분산 1인 정규분포
np.random.randn(2, 4, 5)

# random.randint(low, high, size)
np.random.randint(10, 20, (2, 4))

array([[[-0.96914406, -1.4809011 , -0.52334255,  1.2670646 ,
          0.17241294],
        [-1.22715638, -0.71083024,  0.99516898, -1.31417036,
          0.98698753],
        [-0.47358321, -0.74376164,  1.52516944,  2.10884775,
         -0.61025041],
        [ 0.3683563 , -1.61324268,  0.10014069, -2.32746999,
          0.1008185 ]],

       [[-1.10550215, -1.8986511 ,  1.83865117,  1.44994096,
          1.20240176],
        [ 0.14777913, -0.44447419, -0.22971561, -1.1583668 ,
          0.65702979],
        [-0.37449904,  1.18390413,  0.63067744,  0.27087265,
          0.39346841],
        [ 0.16345804,  0.06928384,  0.41957471, -0.27282427,
          0.03281757]]])

In [ ]:
# random.seed(): 난수 생성시 시작값 제공
np.random.seed(58)
np.random.randn(2, 3)

None
[[-0.76018615 -2.10158401 -0.80975668]
 [-0.00751726 -1.70436077  0.58140398]]


In [40]:
# RNG(Random Number Generator): 최근 Numpy 사용에서 권장되는 방식
from numpy.random import default_rng

rng1 = default_rng(seed = 42)
rng2 = default_rng(seed = 10)

print(rng1.random((3, 2)))
print(rng2.random((3, 2)))

[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]]
[[0.95600171 0.20768181]
 [0.82844489 0.14928212]
 [0.51280462 0.1359196 ]]


In [46]:
# 실습 1-1
np.zeros((3, 4))

np.full((3, 4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [49]:
# 실습 1-2
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [54]:
# 실습 1-3
np.random.rand(2, 3)

array([[0.79506408, 0.59342738, 0.68372708],
       [0.41736994, 0.22726425, 0.28432494]])

In [55]:
# 실습 1-4
m, sigma = 100, 20
m + sigma * np.random.randn(1, 6)

array([[115.69750691,  92.41715281,  80.81254847, 100.47671657,
         89.48540569, 103.76914289]])

In [60]:
# 실습 1-5
A = np.random.randint(1, 20, (1, 20))
B = np.reshape(A, (4, 5))
B

array([[ 4,  9, 13, 10, 13],
       [ 8,  1,  9, 19,  9],
       [ 8, 13,  2,  1, 15],
       [ 3, 15,  7, 14,  4]], dtype=int32)

In [72]:
# 실습 1-6
A = np.linspace(0, 1, 12)
B = np.reshape(A, (3,4))
B

array([[0.        , 0.09090909, 0.18181818, 0.27272727],
       [0.36363636, 0.45454545, 0.54545455, 0.63636364],
       [0.72727273, 0.81818182, 0.90909091, 1.        ]])

In [78]:
# 실습 1-7
A = np.random.randint(0, 100, (10, 10))
B = np.eye(10, 10)

C = A + B
print(A)
print(C)

[[89 70 19  3 41 90 56 49 47 55]
 [ 8 60 36 62 66 85 36 14 63 19]
 [11 49 61 50 82 41  6 99 42 94]
 [97 49  1 99 84 71 45 72 95 32]
 [10 84 55 73 99 46 27 47 66 69]
 [25 47  0 78 44 35 13 40 66 53]
 [10 63 49 50 61 24 40 86 17 34]
 [83 45 19 82 70  5 77 28 52  4]
 [30 77 20 86 68 36 62 72 17 12]
 [39 28 38 23 21 78 66 61 80 21]]
[[ 90.  70.  19.   3.  41.  90.  56.  49.  47.  55.]
 [  8.  61.  36.  62.  66.  85.  36.  14.  63.  19.]
 [ 11.  49.  62.  50.  82.  41.   6.  99.  42.  94.]
 [ 97.  49.   1. 100.  84.  71.  45.  72.  95.  32.]
 [ 10.  84.  55.  73. 100.  46.  27.  47.  66.  69.]
 [ 25.  47.   0.  78.  44.  36.  13.  40.  66.  53.]
 [ 10.  63.  49.  50.  61.  24.  41.  86.  17.  34.]
 [ 83.  45.  19.  82.  70.   5.  77.  29.  52.   4.]
 [ 30.  77.  20.  86.  68.  36.  62.  72.  18.  12.]
 [ 39.  28.  38.  23.  21.  78.  66.  61.  80.  22.]]


In [81]:
A = np.random.randint(0, 10, (2, 3, 4))
A

array([[[4, 3, 4, 0],
        [5, 5, 9, 7],
        [3, 1, 9, 8]],

       [[9, 1, 6, 1],
        [7, 4, 7, 3],
        [6, 2, 9, 7]]], dtype=int32)

### 1-5. 인덱싱과 슬라이싱
- 다차원 배열을 다루는 편의 기능 제공
- Python의 시퀀스보다 빠름

In [82]:
# 인덱싱
a = np.array([10, 20 , 30, 40, 50])
print(a[2])
print(a[-1])

30
50


In [87]:
# 다차원 인덱싱
# 파이썬 리스트
matrix =[[1, 2, 4], [4, 5, 6]]
print("파이썬 인덱싱: ", matrix[1][1])

# numpy 배열
a = np.array([[1, 2 , 4], [4, 5, 6]])
print("numpy 인덱싱: ", a[1, 1])

# 3차원 배열 인덱싱
b = np.arange(24).reshape(2, 3, 4)
print(b)
print("3차원 인덱싱: ", b[1, 1, 1])

파이썬 인덱싱:  5
numpy 인덱싱:  5
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3차원 인덱싱:  17


In [ ]:
# 슬라이싱
# arr[행_슬라이스, 열_슬라이스]
# arr[..., 4차원 슬라이스, 3차원 슬라이스, 2차원 슬라이스, 1차원 슬라이스]

a = np.array([10, 20, 30, 40, 50])
print(a[1:3])
print(a[2:])
print(a[:2])
print(a[::2])
print(a[::-1])

[20 30]
[30 40 50]
[10 20]
[10 30 50]
[50 40 30 20 10]


In [90]:
# 파이썬 리스트와의 차이
# 파이썬 리스트
py_list = [10, 20 , 30 , 40, 50]
sliced = py_list[1:4]
sliced[1] = 100
print("py원본: ", py_list)
print("py슬라이싱: ", sliced)
print()

a = [10, 20 , 30 , 40, 50]
a_sliced = a[1:4]
a_sliced[1] = 100
print("py원본: ", a)
print("py슬라이싱: ", a_sliced)

py원본:  [10, 20, 30, 40, 50]
py슬라이싱:  [20, 100, 40]

py원본:  [10, 20, 30, 40, 50]
py슬라이싱:  [20, 100, 40]


In [95]:
# 실습 2-1
arr = np.arange(10, 30, 2)
arr[1:6:2]

array([12, 16, 20])

In [103]:
# 실습 2-2
arr = np.arange(1, 10).reshape(3, 3)
print(arr)
print(arr[0, 0])
print(arr[1, 1])
print(arr[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
5
9


In [133]:
# 실습 2-3
arr = np.arange(1, 13).reshape(3, 4)
# arr[0, 3] = -1
# arr[1, 3] = -1
# arr[2, 3] = -1

rows, columns = arr.shape
for i in range(rows):
    arr[i, 3] = -1

arr

array([[ 1,  2,  3, -1],
       [ 5,  6,  7, -1],
       [ 9, 10, 11, -1]])

In [134]:
# 실습 2-4
arr = np.arange(1, 17).reshape(4, 4)
print(arr)

rows, columns = arr.shape

# 행 역순
for i in range(rows):
    print(arr[rows -1 -i])

# 열 역순
for i in range(rows):
    arr[i] = arr[i][::-1]
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[13 14 15 16]
[ 9 10 11 12]
[5 6 7 8]
[1 2 3 4]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
