## 02. Numpy

### 2-1. numpy 배열 연산

In [1]:
import numpy as np

In [ ]:
# 배열 간 연산 (1차원)
a1 = np.array([1, 2 ,3])
a2 = np.array([4, 5, 6])

print(a1 + a2)
print(a1 - a2)

[5 7 9]
[-3 -3 -3]


In [ ]:
# 배열 간 연산 (2차원)
a1 = np.arange(1, 5).reshape(2, 2)
a2 = np.arange(11, 15).reshape(2, 2)

print(a1)
print(a2)
print(a1 + a2)
print(a2-a1)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[12 14]
 [16 18]]
[[10 10]
 [10 10]]


In [ ]:
# 배열과 스칼라 연산 (1차원)
a1 = np.array([1, 2, 3, 4])
print(a1 + 10)
print(a1 * 2)

[11 12 13 14]
[2 4 6 8]


In [ ]:
# 배열과 스칼라 연산 (2차원)
a1 = np.arange(1, 5).reshape(2, 2)
a2 = np.arange(11, 15).reshape(2, 2)

print(a1)
print(a2)
print(a1 + 5)
print(a2 * 3)
print(a2 / 2)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[6 7]
 [8 9]]
[[33 36]
 [39 42]]
[[5.5 6. ]
 [6.5 7. ]]


In [ ]:
# 배열의 구조가 다를 경우
a1 = np.array([1, 2])
a2 = np.array([1, 2, 3])
# print(a1 + a2) # ValueError: 행렬의 크기가 맞지 않아 오류 발생

In [ ]:
# 브로드캐스팅
# 자동으로 배열의 크리글 확장 -> 서로 다른 크기의 배열 간 연산을 가능하게 하느 기능
# 1. 두 배열의 차원을 뒤(낮은 차원)에서부터 비교
# 2. 크기가 같거나
# 3. 한 쪽이 1인 경우 확장이 가능

a1 = np.array([[1, 2, 3,], 
               [4, 5, 6]]) # (2, 3)
a2 = np.array([10, 20, 30]) # 길이가 3인 1차원 배열 (3, )

# 1차원 길이 3
[10, 20, 30]

# 2차원으로 변형(1, 3)
[[10, 20, 30]]

# 2차원의 행이 2 -> 2로 확장
[[10, 20, 30], 
 [10, 20, 30]]

print(a1 + a2)

[[11 22 33]
 [14 25 36]]


In [ ]:
# 브로드캐스팅 예제
a1 = np.array([[1], [2], [3]]) # (3, 1)
a2 = np.array([10, 20, 30]) # (3, )

# a2: (3, ) -> (1, 3)로 변환됨
[[10, 20, 30]]

# a1과 a2 비교 -> (3, 1), (1, 3)
[[1, 1, 1], [2, 2, 2], [3, 3, 3]]
[[10, 20, 30], [10, 20, 30], [10, 20, 30]]

print(a1 + a2)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# 실습 1-1
arr = np.array([1, 2, 3, 4])
print(arr + 3)

[4 5 6 7]


In [ ]:
# 실습 1-2 
arr = np.array([[5, 10],
[15, 20]])
print(arr * (-1))

[[ -5 -10]
 [-15 -20]]


In [ ]:
# 실습 1-3
arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 2, 3])
print(arr1 * arr2)
print(arr1 / arr2)

[ 2  8 18]
[2. 2. 2.]


In [ ]:
# 실습 1-4
arr = np.array([[95, 97],
[80, 85]])
print(100 - arr)

[[ 5  3]
 [20 15]]


In [ ]:
# 실습 1-5
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, :] * 10, arr[1, :] * 100)

[10 20 30] [400 500 600]


In [ ]:
# 실습 1-6
arr = np.array([[10, 20],
[30, 40],
[50, 60]])
arr1d = np.array([100, 200, 300]).reshape(3, 1)
print(arr + arr1d)

[[110 120]
 [230 240]
 [350 360]]


### 2-2. 통계 함수 및 집계 연산

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print("원소의 합:", np.sum(a))
print("원소의 평균", np.mean(a))
print("표준편차:", np.std(a))
print("최댓값:", np.max(a))
print("최솟값:", np.min(a))
print("최댓값의 인덱스:", np.argmax(a))
print("최솟값의 인덱스:", np.argmin(a))

원소의 합: 21
원소의 평균 3.5
표준편차: 1.707825127659933
최댓값: 6
최솟값: 1
최댓값의 인덱스: 5
최솟값의 인덱스: 0


In [ ]:
# 축(axis) 단위 연산

# axis = 0 -> 가장 높은 차원 기준 -> 행 기준
# + 행 기준 = 행을 따라 연산 = 행을 증가시키며 연산

# axis = 1 -> 그 다음에 가장 높은 차원 기준 -> 열 기준
# + 열 기준 = 열을 따라 연산 = 열을 증가시키며 연산

a = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])
print("행기준 합", np.sum(a, axis = 0))
print("열기준 합", np.sum(a, axis = 1))
print("행기준평균", np.mean(a, axis = 0))
print("열기준평균", np.mean(a, axis = 1))

행기준 합 [12 15 18]
열기준 합 [ 6 15 24]
행기준평균 [4. 5. 6.]
열기준평균 [2. 5. 8.]


In [ ]:
# 누적 연산
arr = np.array([1, 2, 3, 4])
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 1  3  6 10]
[ 1  2  6 24]


In [ ]:
# 실습 2-1
arr = np.array([5, 10, 15, 20])
print("합",np.sum(arr))
print("평균", np.mean(arr))

50
12.5


In [ ]:
# 실습 2-2
arr = np.array([[3, 7, 1],
[9, 2, 8]])
print("최댓값", np.max(arr))
print("최솟값", np.min(arr))

최댓값 9
최솟값 1


In [ ]:
# 실습 2-3
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

print("행기준 합", np.sum(arr, axis = 0))
print("열기준 합", np.sum(arr, axis = 1))

행기준 합 [12 15 18]
열기준 합 [ 6 15 24]


In [ ]:
# 실습 2-4
arr = np.array([[10, 20],
[30, 40],
[50, 60]])
print("행 기준 평균", np.mean(arr, axis = 0))
print("열 기준 평균", np.mean(arr, axis = 1))

행 기준 평균 [30. 40.]
열 기준 평균 [15. 35. 55.]


In [ ]:
# 실습 2-5
arr = np.array([2, 4, 4, 4, 5, 5, 7, 9])
print("표준편차", np.std(arr))
print("평균", np.mean(arr))
print("편차", arr - np.mean(arr))

표준편차 2.0
평균 5.0
편차 [-3. -1. -1. -1.  0.  0.  2.  4.]


In [ ]:
# 실습 2-6
arr = np.array([[1, 2, 3],
[4, 5, 6]])
print("행 단위 누적 합", np.cumsum(arr, axis = 0))
print("열 단위 누적 곱", np.cumprod(arr, axis = 1))

행 단위 누적 합 [[1 2 3]
 [5 7 9]]
열 단위 누적 곱 [[  1   2   6]
 [  4  20 120]]


### 2-3. 논리 연산과 조건 연산

In [ ]:
# np.where()
# 조건 기반 선택 함수

arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr > 30, "High", "Low")
result

array(['Low', 'Low', 'Low', 'High', 'High'], dtype='<U4')

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
# 조건만 넣을 경우 조건을 만족하는 원소의 인덱스르 반환
result = np.where(arr > 30)
print(result)
print(arr[result]) # Fancy Indexing

(array([3, 4]),)
[40 50]


In [ ]:
# 논리 연산
# and: & - 모든 조건이 True여야 True
# or: | - 모든 조건 중 하나라도 True면 True
# not: ~ - 조건 반대 값

# and 연산 (&)
arr = np.array([10, 20, 30, 40, 50])
mask_and = (arr > 10) & (arr < 50)
print("&연산", arr[mask_and])

# or 연산 (|)
mask_or = (arr < 20) | (arr > 40)
print("|연산", arr[mask_or])

# not 연산 (~)
mask_not = ~(arr > 30)
print("~연산", arr[mask_not])

&연산 [20 30 40]
|연산 [10 50]
~연산 [10 20 30]


In [ ]:
# 실습 3-1
arr = np.array([5, 12, 18, 7, 30, 25])
print(arr[(arr > 10) & (arr < 20)])

[12 18]


In [ ]:
# 실습 3-2
arr = np.array([10, 15, 20, 25, 30, 35])
print(arr[(arr <= 15) | (arr >= 30)])

[10 15 30 35]


In [ ]:
# 실습 3-3
arr = np.array([3, 8, 15, 6, 2, 20])
arr[arr >= 10] = 0
print(arr)

[3 8 0 6 2 0]


In [ ]:
# 실습 3-4
arr = np.array([7, 14, 21, 28, 35])
result = np.where(arr >= 20, "High", "Low")
print(result)

['Low' 'Low' 'High' 'High' 'High']


In [ ]:
# 실습 3-5
arr = np.arange(0, 10)
arr_odd = np.where(arr % 2 == 0, arr * 10, arr)
print(arr_odd)

[ 0  1 20  3 40  5 60  7 80  9]


In [ ]:
# 실습 3-6
arr = np.array([[10, 25, 30],
                [40, 5, 15],
                [20, 35, 50]])
arr_condition = np.array(arr[(20 <= arr) & (arr <= 40)])
print(arr_condition)

[25 30 40 20 35]


In [ ]:
# 실습 3-7
arr = np.array([1, 2, 3, 4, 5, 6])
# arr_3 = np.where(arr[arr % 3 != 0])
print(arr[arr % 3 != 0])

[1 2 4 5]


In [ ]:
# 실습 3-8
arr = np.arange(0, 100).reshape(10, 10)
arr_change = np.where(arr >= 50, arr, 50)
print(arr_change)

[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
# 실습 3-9
arr = np.array([[5, 50, 95],
[20, 75, 10],
[60, 30, 85]])
arr_change = np.where(arr >= 70, "A", np.where(arr >= 30, "B", "C"))
print(arr_change)

[['C' 'B' 'A']
 ['C' 'A' 'C']
 ['B' 'B' 'A']]


### 2-4. 행렬 곱셈
- 두 행렬을 곱해서 새로운 행렬을 생성하는 연산
- 첫 번째 행렬의 열수와 두 번째 행렬의 행수가 같아 야 곱셈이 가능함
- np.dot(), np.matmul() 사용

In [ ]:
# np.dot(a, b): 배열의 내적 연산
# 스칼라 연산(OD)
a = np.array(3)
b = np.array(4)
print(np.dot(a, b))

12


In [ ]:
# 1차원 배열 간 연산 -> 내적
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))

# 물건 구매
# 데이터 분석에서 벡터랑 배열
c = [1000, 2000, 5000, 10000]
d = [10, 3, 5, 7]
print(np.dot(c, d))

32
111000


In [ ]:
# 2차원 배열간 연산 -> 행렬 곱셈
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])
print(np.dot(a,b))

[[22 28]
 [49 64]]


In [ ]:
# np.matmul(a, b)
# Matrix Multiplication
# 스칼라 연산 시도 시 에러
a = np.array(3)
b = np.array(4)
# print(np.matmul(a, b))

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
# 1차원 배열간 연산 -> 내적
a = np.array([1, 2])
b = np.array([3, 4])
print(np.matmul(a, b))

11


In [ ]:
# 2차원 배열간 연산 -> 행렬 곱셈
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])
print(np.matmul(a,b))

# 2차원 * 1차원 간 연산
c = np.array([[1, 2], [3, 4]])
d = np.array([5, 6])
print(np.matmul(c, d))
print(np.matmul(d, c))

# @ 연산자
e = np.array([[1, 2, 3]])
f = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(np.matmul(e, f))
print(e @ f)

[[22 28]
 [49 64]]
[17 39]
[23 34]
[[22 28]]
[[22 28]]


In [ ]:
# 실습 4-1
A = np.arange(1, 10).reshape(3, 3)
B = np.full((3, 2), 2)
print(A)
print(B)
print(np.matmul(A, B))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2]
 [2 2]
 [2 2]]
[[12 12]
 [30 30]
 [48 48]]


In [ ]:
# 실습 4-2
I= np.eye(4, 4)
M = np.random.randint(0, 9, (4, 4))
print(np.matmul(I, M))
print(M)

[[1. 1. 0. 1.]
 [3. 8. 0. 6.]
 [2. 8. 4. 6.]
 [5. 5. 0. 5.]]
[[1 1 0 1]
 [3 8 0 6]
 [2 8 4 6]
 [5 5 0 5]]


In [ ]:
# 실습 4-3
X = np.ones((2, 5))
Y = np.arange(5, 15).reshape(5, 2)
print(X @ Y)

NameError: name 'np' is not defined

In [ ]:
# 실습 4-4
C = np.random.randint(0, 5, (3, 2))
D = np.random.randint(0, 5, (2, 3))
print((np.matmul(C, D)).shape)

(3, 3)
