In [1]:
# 1. 넘파이 모듈을 np라는 이름으로 임포트해보세요.
import numpy as np

In [ ]:
# 2. 리스트를 넘파이의 ndarray 객체로 변환해보세요.
data = [1, 2, 3]
dt = np.ndarray(data)
print(dt)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [2.22520967e-306 1.89146896e-307 7.56571288e-307]]]


In [ ]:
# 3. 0부터 99까지의 정수가 저장된 ndarray 객체를 만들어 보세요.
np.ndarray(100)

array([0.00000000e+000, 0.00000000e+000, 4.94065646e-324, 6.95259203e-310,
       4.69362364e-322, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18063972e-311, 1.18063972e-311, 1.18064283e-311,
       1.18063972e-311, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18064283e-311, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18063972e-311, 1.18064283e-311, 1.18063972e-311,
       1.18063972e-311, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18064283e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18064283e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18064283e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1

In [ ]:
# 4. 구구단 3단의 결과가 저장된 ndarray 객체를 만들어 보세요
arr = np.arange(1,10) * 3
print(arr)

[ 3  6  9 12 15 18 21 24 27]


In [ ]:
# 5. 1000보다 작은 짝수가 저장된 ndarray 객체를 만들어 보세요.
arr = np.arange(1000)
arr[arr % 2 == 0]
# np.arange(2, 1000, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [ ]:
# 6. 0부터 1까지 0.1 간격으로 구성된 ndarray를 생성해보세요. 1은 포함되지 않습니다.
arr = np.arange(0, 1, 0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
# 7. 리스트에는 6개의 데이터가 저장돼 있습니다. 2행 3열의 ndarray로 변환하세요.
data = [0, 1, 2, 3, 4, 5]
arr = np.array(data)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 8. 다음의 2차원 ndarray 1차원 ndarray로 변환하세요.
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.flatten()

array([0, 1, 2, 3, 4, 5])

In [ ]:
# 9. 주어진 ndarray를 3행 1열로 변환하세요.
arr = np.arange(3)
arr.reshape(3, 1)


array([[0],
       [1],
       [2]])

In [25]:
# 10. 에러의 원인을 설명하세요.
# > np.arange(6).reshape(2, 4)
# ValueError: cannot reshape array of size 6 into shape (2,4)

# --> arange(6)에 의해 총 6개의 데이터가 저장된 ndarray가 생성된다. 이를 2행 4열의 행렬로 변환하려 했기 때문에 데이터의 갯수가 달라 에러가 발생한 것이다.

In [4]:
# 11. 2차원 ndarray 객체를 정의하세요.
data = [
    [0, 1, 2],
    [3, 4, 5]
]

arr = np.array(data)
# orrrrr
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
# 12. 1이 20개 저장된 아래의 ndarray 객체를 만들어 보세요.
arr = np.ones(20,)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
# 13. 4행 5열이며 1로만 구성된 ndarray 객체를 만들어 보세요.

arr = np.ones((4, 5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 14. 255로 채워진 10X10 크기의 ndarray 객체를 생성하세요.
arr = np.ones((10, 10))
arr = arr * 255
arr

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

In [ ]:
# 15. 3x4 (행x열) 크기의 0으로 채워진 배열을 생생해보세요.
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 16. [1, 2, 3]을 np.int32 타입의 ndarray 배열로 생성하세요.
arr = np.ndarray([1, 2, 3], dtype=np.int32)
arr

array([[[          0,           0,    89947600],
        [        599,           0, -2147483648]]], dtype=int32)

In [ ]:
# 17. 다음 배열의 데이터 타입을 확인해보세요.
arr = np.array([1, 2, 3])
print(arr.dtype)

int64


In [ ]:
# 18. 다음 배열의 데이터 타입을 확인해보세요.
arr = np.array(['1', '2', '3'])
print(arr.dtype)

<U1


In [ ]:
# 19. 다음 데이터를 np.int16 타입의 배열로 형변환하세요.
arr = np.array([1, 2, 3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

In [ ]:
# 20. 300이 44로 출력되는 이유를 설명하세요.
# > a = np.array( [ 255, 300, 128], dtype=np.uint8 )
# > a
# [255  44 128]

In [20]:
# 21. arr 배열은 float64 타입입니다. 이를 np.int32 타입으로 변경하세요.
arr = np.array([1.1, 2.1, 3.1])
arr.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [23]:
# 22. 0~10 사이를 구간을 20개의 포인트로 분할한 결과를 ndarray로 표현하라.
array = ([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])
arr = np.linspace(0, 10, 20)
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
# 23. 다음의 ndarry 객체에서 마지막 로우([6, 7, 8])을 출력하세요.
arr = np.arange(9).reshape(3, 3)
arr[2]

array([6, 7, 8])

In [25]:
# 24. 다음의 ndarry 객체에서 두 번째 컬럼([1, 4, 7])을 출력하세요.
arr = np.arange(9).reshape(3, 3)
arr[:, 1]

array([1, 4, 7])

In [27]:
# 25. 다음의 ndarray 객체에서 17을 선택하는 코드를 작성하라.
arr = np.arange(25).reshape(5, 5)
arr[3, 2]

np.int64(17)

In [28]:
# 26. [1 3]을 슬라이싱 하는 코드를 작성하세요.
arr = np.arange(5)
arr[1::2]

array([1, 3])

In [29]:
# 27. [6 7 8 9]를 슬라이싱 하는 코드를 작성하세요.
arr = np.arange(25).reshape(5, 5)
arr[1, 1:]

array([6, 7, 8, 9])

In [32]:
# 28. 첫번째와 두번째 컬럼을 슬라이싱하는 코드를 작성하세요.
arr = np.arange(25).reshape(5, 5)
arr[:, 0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [ ]:
# 29. 6, 7, 11, 12 를 2x2 ndarray로 슬라이싱하는 코드를 작성하세요.
arr = np.arange(25).reshape(5, 5)
arr[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [34]:
# 30. 0, 3, 20, 23 를 2x2 ndarray로 슬라이싱하는 코드를 작성하세요.
arr = np.arange(25).reshape(5, 5)
arr[0::4, 0::3]


array([[ 0,  3],
       [20, 23]])

In [38]:
# 31. 전체 데이터에 10을 곱한 결과를 ndarray에 저장하세요.
data = [1, 2, 3]
arr = np.array(data) * 10
arr

array([10, 20, 30])

In [40]:
# 32. 전체 데이터에 제곱한 결과를 ndarray에 저장하세요.
data = [1, 2, 3]
arr = np.array(data) ** 2
arr

array([1, 4, 9])

In [42]:
# 33. 전체 데이터에 루트를 적용한 결과를 ndarray에 저장하세요.
data = [1, 2, 3]
arr = np.array(data) ** 0.5
arr

array([1.        , 1.41421356, 1.73205081])

In [43]:
# 34-35. 다음 ndarray에는 중간고사의 국어점수(10), 영어점수(20), 기말고사의 국어점수(14), 영어점수(16)이 저장돼 있습니다.
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

In [47]:
# 34.과목별 평균 점수를 출력하세요.
mean_score = score.mean(axis=0)
print(mean_score)

[12. 18.]


In [49]:
# 35. 중간고사와 기말고사의 표준편차를 출력하세요.
std_score = score.std(axis=1)
print(std_score)

[5. 1.]


In [51]:
# 36. 두 행렬의 곱셉결과를 출력하세요.
a = np.arange(4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)
print(a @ b)

[[ 3  4]
 [11 16]]


In [53]:
# 37. 다음의 ndarray로 행과 열의 위치를 바꾼 전치행렬을 출력하세요.
arr = np.arange(9).reshape(3, 3)
arr_transpose = arr.T # or arr.transpose()
print(arr_transpose)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [54]:
# 38. 다음 배열에서 짝수 값만 추출하세요.
arr = np.arange(10)
arr[0::2]

array([0, 2, 4, 6, 8])

In [55]:
# 39. 다음 배열에서 짝수 값만 추출하세요.
arr = np.arange(10)
arr[1::2]

array([1, 3, 5, 7, 9])

In [59]:
# 40. 다음 배열에서 3보다 크고 7보다 작은수만 추출하세요
arr = np.arange(10)
arr[(3 < arr) & (arr < 7)]

array([4, 5, 6])

In [60]:
# 41. 다음 ndarray 객체에서 음수를 출력하세요.
arr = np.array([-1, 2, -3, 4])
arr[arr < 0]

array([-1, -3])

In [62]:
# 42. 다음 ndarray 객체에서 음수를 0으로 치환하세요.
arr = np.array([-1, 2, -3, 4])
arr[arr < 0] = 0
arr

array([0, 2, 0, 4])

In [63]:
# 43. 다음 ndarray 객체에서 음수를 양수로 변환하세요.
arr = np.array([-1, 2, -3, 4])
arr[arr < 0] = -arr[arr < 0]
arr

array([1, 2, 3, 4])

In [ ]:
# 44. 다음 ndarray 객체에서 양수 혹은 0이면 10을 더하고 음수는 10을 빼세요.
arr = np.array([-1, 2, -3, 4])
cond1 = arr < 0
cond2 = arr > 0
arr[cond1] += 10
arr[cond2] -= 10
arr
# np.where(arr >= 0, arr + 10, arr - 10)

array([ 9, -8,  7, -6])

In [69]:
# 45. numpy random 모듈의 shuffle 함수를 사용해서 입력 리스트의 원소들을 랜덤하게 섞어 보세요.
import random
arr = [1, 2, 3, 4, 5]
random.shuffle(arr)
print(arr)

[5, 3, 4, 2, 1]


In [73]:
# 46. 다음 넘파일 배열에서 최솟값의 인덱스를 출력하세요.
arr = np.array([1, 2, 3, 4, 5])
print(np.argmin(arr))

0


In [74]:
# 47. 다음 넘파일 배열에서 최댓값의 인덱스를 출력하세요.
arr = np.array([1, 2, 3, 4, 5])
print(np.argmax(arr))

4


In [75]:
# 48. 다음 넘파이 배열을 오름차순 정렬해보세요.
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
# 49. numpy.vstack 함수를 사용하여 다음 2차원 배열을 생성하세요.
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
np.vstack((arr1, arr2))

array([[1, 2],
       [3, 4]])

In [81]:
# 50. flatten 메서드를 사용하여 다음 배열을 1차원 배열로 변경하세요.
arr = np.array([ [1, 2], [3, 4] ])
arr.flatten()

array([1, 2, 3, 4])

In [1]:
# 51. 판다스의 시리즈 클래스를 사용하기 위해 주로 사용하는 두 가지 방식으로 임포트해보세요.
import pandas as pd
from pandas import Series

In [2]:
# 52. 다음 데이터를 시리즈로 객체로 생성해보세요.
data = [100, 200, 300]
s = Series(data)
print(s)

0    100
1    200
2    300
dtype: int64


In [ ]:
# 53. 생성된 시리즈 객체에 인덱스를 추가해보세요.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
# s = Series(data)
# s.index = index
print(s)

100    철수
200    영희
300    아름
dtype: object


In [5]:
# 54.  다음 데이터를 파이썬 딕셔너리로 표현해보세요. 딕셔너리의 key로 인덱스를 value로 점수 컬럼을 지정하세요. 생성된 딕셔너리를 사용하여 시리즈 객체를 생성해봅시다.
score = {"철수": 100, "영희": 200, "아름": 300}
s = Series(score)
print(s)

철수    100
영희    200
아름    300
dtype: int64


In [6]:
# 55. 다음은 네이버 금융에서 특정 거래일의 인기 종목과 해당 종목의 종가 데이터입니다. 종목명을 인덱스로 하여 종가를 데이터로 지정하여 시리즈 객체를 생성해봅시다.
stock = ["삼성전자", "셀트리온", "카카오", "삼성전자우", "현대바이오"]
price = [73000, 356000, 367000, 68600, 34150]
s = Series(price, stock)
print(s)

삼성전자      73000
셀트리온     356000
카카오      367000
삼성전자우     68600
현대바이오     34150
dtype: int64


In [11]:
# 56. 시리즈에 저장된 인덱스만을 출력해보세요.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.index)

Index(['철수', '영희', '아름'], dtype='object')


In [15]:
# 57. 인덱스 없이 시리즈에 저장된 데이터만을 출력해보세요.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.values)

[100 200 300]


In [16]:
# 58. 시리즈를 딕셔너리로 변경해 보세요.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.to_dict())

{'철수': 100, '영희': 200, '아름': 300}


In [ ]:
# 59. 시리즈를 엑셀 파일(data.xlsx)에 저장해 보세요.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
s.to_excel("data.xlsx")
# 위 엑셀에서 첫 번째 라인을 제거하고싶다면?
# s.to_excel("data.xlsx", header=False)

In [ ]:
# 60. 엑셀 파일(data.xlsx)을 읽어 오세요.
pd.read_excel("data.xlsx")

Unnamed: 0    0
0         철수  100
1         영희  200
2         아름  300

: 