In [ ]:
# 1. 넘파이 모듈을 np라는 이름으로 임포트해보세요.
import numpy as np

In [ ]:
# 2. 리스트를 넘파이의 ndarray 객체로 변환해보세요.
data = [1, 2, 3]
dt = np.ndarray(data)
print(dt)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [2.22520967e-306 1.89146896e-307 7.56571288e-307]]]


In [ ]:
# 3. 0부터 99까지의 정수가 저장된 ndarray 객체를 만들어 보세요.
np.ndarray(100)

array([0.00000000e+000, 0.00000000e+000, 4.94065646e-324, 6.95259203e-310,
       4.69362364e-322, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18063972e-311, 1.18063972e-311, 1.18064283e-311,
       1.18063972e-311, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18064283e-311, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18063972e-311, 1.18064283e-311, 1.18063972e-311,
       1.18063972e-311, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18064283e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18064283e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18064283e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1.18063972e-311, 1.18063972e-311, 1.18063972e-311,
       1.18063972e-311, 1

In [ ]:
# 4. 구구단 3단의 결과가 저장된 ndarray 객체를 만들어 보세요
arr = np.arange(1,10) * 3
print(arr)

[ 3  6  9 12 15 18 21 24 27]


In [ ]:
# 5. 1000보다 작은 짝수가 저장된 ndarray 객체를 만들어 보세요.
arr = np.arange(1000)
arr[arr % 2 == 0]
# np.arange(2, 1000, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [ ]:
# 6. 0부터 1까지 0.1 간격으로 구성된 ndarray를 생성해보세요. 1은 포함되지 않습니다.
arr = np.arange(0, 1, 0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
# 7. 리스트에는 6개의 데이터가 저장돼 있습니다. 2행 3열의 ndarray로 변환하세요.
data = [0, 1, 2, 3, 4, 5]
arr = np.array(data)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 8. 다음의 2차원 ndarray 1차원 ndarray로 변환하세요.
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.flatten()

array([0, 1, 2, 3, 4, 5])

In [ ]:
# 9. 주어진 ndarray를 3행 1열로 변환하세요.
arr = np.arange(3)
arr.reshape(3, 1)


array([[0],
       [1],
       [2]])

In [25]:
# 10. 에러의 원인을 설명하세요.
# > np.arange(6).reshape(2, 4)
# ValueError: cannot reshape array of size 6 into shape (2,4)

# --> arange(6)에 의해 총 6개의 데이터가 저장된 ndarray가 생성된다. 이를 2행 4열의 행렬로 변환하려 했기 때문에 데이터의 갯수가 달라 에러가 발생한 것이다.

In [ ]:
# 11. 4행 5열이며 1로만 구성된 ndarray 객체를 만들어 보세요.

